spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.22.176/sell?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://192.168.199.120/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: true
  jackson:
    default-property-inclusion: non_null
#logging:
#  pattern:
##    console: "%d -%msg%n"
#  file: /var/log/tomcat/sell.log
#  level: debug
server:
  port: 8080
  context-path: /sell


wechat:
  # 公众账号，授权
  mpAppId: wxd898fcb01713c658
  mpAppSecret: a932a6bb93bc8a229d50c566984e53b6
#  mpAppId: wx4b0594326d23c9e2
#  mpAppSecret: a932a6bb93bc8a229d50c566984e53b6
  #开放平台，卖家扫码登录用
  openAppId: 
  openAppSecret:
  #支付/商户号
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  # 发起支付不需要证书，退款需要
  keyPath:
  notifyUrl: http://wyxsell.natapp1.cc/sell/pay/notify
